version: "3.5"

services:
    application:
        container_name: "${APPLICATION_CONTAINER_NAME:-glpi}"
        restart: "${APPLICATION_CONTAINER_RESTART_POLICY:-unless-stopped}"
        build:
            context: "containers/glpi"
            args:
                BASE_IMAGE: "${APPLICATION_CONTAINER_BASE_IMAGE:-php:apache-buster}"
                HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
                HOST_USER_ID: "${HOST_USER_ID:-1000}"
        networks:
            default:
                ipv4_address: 172.20.0.2
                aliases:
                    - "${APPLICATION_NETWORK_ALIAS:-glpi.local}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "80:80"
        volumes:
            - type: "bind"
              source: "${APPLICATION_HOME:-./mounts/application/home/www-data}"
              target: "/home/www-data"
            - type: "bind"
              source: "${APPLICATION_PATH:-./mounts/application/var/www/glpi}"
              target: "/var/www/glpi"

networks:
    default:
        driver: "bridge"
        name: "${NETWORK_NAME:-glpi_bridge}"
        ipam:
            config:
                - subnet: "172.20.0.1/16"

